configuration: Release

image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "3.3.0-ci.$($env:APPVEYOR_BUILD_NUMBER)+sha.$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

cache:
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'
  - packages -> **\packages.config

before_build:
  - nuget restore -Verbosity quiet

build:
  parallel: true
  verbosity: minimal

artifacts:
  - path: 'src\**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: Sn05A/FiUAlID5v31uaf5EZuYCSo4frLONtrCY+cwY265dU2JUZsl2+sjVeLQyz/
  on:
    appveyor_repo_tag: true
