using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Web.Mvc: MVC3 extension for Ninject")]
[assembly: AssemblyCompanyAttribute("bbv Software Services AG")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2010 bbv Software Services AG and contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.26")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

